# License: Apache 2.0
# Author: Manuel Hernandez Giuliani
# Date Created: 2026-03-22
# Date Modified: 2026-03-22
# Purpose: Minimal dbt project starter for the ingestion-s3-to-redshift-dbt example covering DP-EH Bronze, Silver, and Gold-ready transformations.
# Architecture component: DP-EH - Data Processing Center - Enterprise Hub

name: "ingestion_s3_to_redshift_dbt"
version: "1.0.0"
config-version: 2

profile: "ingestion_s3_to_redshift_dbt"

model-paths: ["models"]

models:
  ingestion_s3_to_redshift_dbt:
    +materialized: view
    staging:
      +schema: bronze
      +tags: ["bronze", "staging"]
    intermediate:
      +schema: silver
      +tags: ["silver", "intermediate"]
    curated:
      +schema: gold
      +tags: ["gold", "curated", "gold-ready"]
